version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
  python:
    build: .
    command: pytest --alluredir=/app/allure_results
    volumes:
      - ./test_cases:/app/test_cases
      - ./allure_results:/app/allure_results
    depends_on:
      - mysql
